[package]
name = "lab_5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1.29"
num-primes = "0.3.0"
mod_exp = "1.0.1"
