[package]
name = "lab_6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
mod_exp = "1.0.1"
num = "0.1.29"
num-primes = "0.3.0"
num-bigint = "0.4.3"
